context:
  version: "0.4.0"

package:
  name: edgehop
  version: ${{ version }}

source:
  url: https://github.com/ytausch/edgehop/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8580c46d98b158b514e8ec9460737b68c7ea4496ee563895f7fe1487817f4c86

build:
  number: 0
  # edgehop only supports macOS and Windows
  skip: linux
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script: edgehop --help
  - package_contents:
      bin:
        - edgehop
      strict: true

about:
  homepage: https://github.com/ytausch/edgehop
  summary: Switch Logitech Easy-Switch devices when the cursor hits a screen edge
  description: |
    Push the mouse cursor against an outer edge of the screen, and your Logitech
    Easy-Switch keyboard and mouse switch to another computer.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/ytausch/edgehop

extra:
  recipe-maintainers:
    - ytausch
